server:
  port: 2910

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://35.240.226.176:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  application:
    name: auth-service

eureka:
  instance:
    preferIpAddress: true
    hostname: 10.148.0.10
  client:
    service-url:
      defaultZone: http://10.148.0.10:8761/eureka/



