server:
  port: 2910

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://35.247.170.16:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  application:
    name: auth-service

eureka:
  instance:
#    preferIpAddress: true
    hostname: 35.247.174.194
  client:
    service-url:
      defaultZone: http://35.247.174.194:8761/eureka/



